services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos
    hostname: nacos
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
    volumes:
      - $PWD/configs/nacos/application.properties:/home/nacos/conf/application.properties
      - $PWD/data/nacos/log:/home/nacos/logs
    networks:
      proxy:
        ipv4_address: ${NACOS_IPV4_ADDRESS}
    ports:
      - 8848:8848

  prometheus:
    image: bitnami/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    hostname: prometheus
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - $PWD/configs/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - $PWD/data/prometheus/data:/opt/bitnami/prometheus/data
    networks:
      proxy:
        ipv4_address: ${PROMETHEUS_IPV4_ADDRESS}
    ports:
      - 9090:9090
    depends_on:
      - nacos

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    hostname: grafana
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - $PWD/data/grafana/data:/var/lib/grafana
    networks:
      proxy:
        ipv4_address: ${GRAFANA_IPV4_ADDRESS}
    ports:
      - 3000:3000
    depends_on:
      - prometheus

networks:
  proxy:
    driver: bridge
    name: AIoT
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1
